import { Footer } from "@/components/footer"
import { Navbar } from "@/components/navbar"

const sections = [
  { title: "1. Notre engagement", content: "Gallé Connect Pro respecte la confidentialité des personnes qui utilisent son site et sa plateforme. Cette politique explique quelles données nous traitons, pourquoi nous les utilisons et quels choix vous pouvez exercer." },
  { title: "2. Données collectées", content: "Nous pouvons collecter les informations que vous nous transmettez lors d’une prise de contact, d’une demande de souscription ou de l’utilisation de la plateforme : nom, adresse e-mail professionnelle, téléphone, nom de l’agence, pays, ville, informations de facturation et échanges avec le support. Les agences clientes peuvent également renseigner des données relatives à leurs agents, clients, prospects, propriétaires, biens, visites, contrats et factures." },
  { title: "3. Finalités du traitement", content: "Ces données sont utilisées pour répondre à vos demandes, gérer les abonnements et paiements, fournir et améliorer la plateforme, assurer son bon fonctionnement et sa sécurité, vous accompagner via le support et respecter nos obligations légales." },
  { title: "4. Rôle des agences clientes", content: "Pour les données de clients, prospects, propriétaires ou agents renseignées par une agence dans Gallé Connect Pro, l’agence concernée reste responsable de la collecte et des finalités de traitement. Gallé Connect Pro intervient uniquement pour fournir et sécuriser le service conformément aux instructions de l’agence." },
  { title: "5. Partage et sous-traitants", content: "Nous ne vendons pas vos données personnelles. Nous pouvons faire appel à des prestataires techniques nécessaires au fonctionnement du service, par exemple pour l’hébergement, l’envoi d’e-mails ou la maintenance. Ces prestataires n’accèdent aux données que dans la mesure nécessaire à leur mission et avec des garanties appropriées." },
  { title: "6. Conservation", content: "Nous conservons les données pendant la durée nécessaire à la fourniture du service, à la gestion de la relation commerciale et au respect de nos obligations. À la clôture d’un compte, les données sont supprimées ou anonymisées selon les délais applicables, sauf obligation légale ou nécessité de conservation justifiée." },
  { title: "7. Sécurité", content: "Nous mettons en place des mesures techniques et organisationnelles raisonnables pour protéger les données contre l’accès non autorisé, la perte, l’altération ou la divulgation. Aucune transmission ou conservation électronique ne peut toutefois être garantie comme totalement exempte de risque." },
  { title: "8. Vos droits", content: "Selon la réglementation applicable, vous pouvez demander l’accès, la rectification, la suppression, la limitation ou l’opposition au traitement de vos données. Pour exercer ces droits ou poser une question, écrivez à support@galleconnect.com. Nous pourrons demander une information raisonnable pour vérifier votre identité." },
  { title: "9. Cookies", content: "Le site peut utiliser des cookies ou technologies similaires nécessaires à son fonctionnement et, le cas échéant, à la mesure de son audience. Vous pouvez gérer certains cookies depuis les réglages de votre navigateur." },
  { title: "10. Modifications", content: "Cette politique peut évoluer en fonction des changements du service ou des exigences applicables. La version publiée sur cette page est la version en vigueur." },
]

export default function PolitiqueConfidentialitePage() {
  return <><Navbar /><main className="bg-background py-16 md:py-24"><article className="mx-auto max-w-3xl px-6"><p className="text-sm font-semibold uppercase tracking-widest text-[#d99306]">Légal</p><h1 className="mt-3 font-serif text-4xl font-bold text-[#374250] md:text-5xl">Politique de confidentialité</h1><p className="mt-5 text-sm text-muted-foreground">Dernière mise à jour : 11 septembre 2026</p><p className="mt-8 text-lg leading-relaxed text-[#3a3a3a]">Cette politique de confidentialité s’applique au site et à la plateforme Gallé Connect Pro, solution de gestion destinée aux agences immobilières.</p><div className="mt-12 space-y-10">{sections.map((section) => <section key={section.title}><h2 className="font-serif text-2xl font-bold text-[#374250]">{section.title}</h2><p className="mt-3 leading-7 text-[#3a3a3a]">{section.content}</p></section>)}</div></article></main><Footer /></>
}
